### ISSUE TITLE
Player Record

### ISSUE THREAD

**Issue by w136111526** [aliakseis/FFmpegPlayer#10]
I want to record the video playing part. Does your player support this function?

**Comment by aliakseis** [comment]
Sorry, it is not clear: do you mean a possibility to select and save a part of the video? No, it is not implemented, but it could be a good feature request.

**Comment by w136111526** [comment]
Yes, I want video players to have more powerful features, such as saving videos, fast forward, fast back, twice the speed of playing, 0.5 times the speed of playing these features, but I do not know how to do.

**Comment by xixihao123** [comment]
I also want to play the video at twice the speed. How can I modify this project?

**Comment by aliakseis** [comment]
Sorry, I am on it but don't have time to implement features fully yet. For now, you can set SPEED_COEFF = 2 to play the video at twice the speed

**Comment by aliakseis** [comment]
Seems to be implemented as for prototype. Please ping me if you have issues/ideas.
