### ISSUE TITLE
play speed abnormal

### ISSUE THREAD

**Issue by xixihao123** [aliakseis/FFmpegPlayer#18]
Hello, I use your video player to play video with audio. When I unplug the headset during playing, the video speed becomes abnormal, why?

**Comment by xixihao123** [comment]
Hello, I just tried ffplay to unplug the headset will not be this situation, I would like to ask you this audio implementation can be changed to SDL?

**Comment by xixihao123** [comment]
Hello, I just tried again, playing files with audio and video, pull out the ear during the play, the following situation occurred: 1. When using Audio Player Impl to achieve audio playback, it will cause video playback to be very delayed. 2. When using Audio Player Wasapi to achieve audio playback, Will make the video play fast.

**Comment by aliakseis** [comment]
Probably the situation is being treated as some audio output error and the audio thread either hangs here
https://github.com/aliakseis/FFmpegPlayer/blob/49f6da5f9827a5e25716476ac19c77e92fb17f97/Player/AudioPlayerWasapi.cpp#L363
or fails here:
https://github.com/aliakseis/FFmpegPlayer/blob/49f6da5f9827a5e25716476ac19c77e92fb17f97/Player/AudioPlayerImpl.cpp#L198
I observed similar behavior, however only when something serious happened, like manual audio driver disabling or sudden failure after system hibernation...

**Comment by xixihao123** [comment]
But why would ffplay.exe of ffmpeg not have this situation?

**Comment by w136111526** [comment]
@xixihao123 I have find the same issue when pull out the ear during the play

**Comment by aliakseis** [comment]
Seems to be fixed.

**Comment by xixihao123** [comment]
It's OK， thank you very much!

**Comment by aliakseis** [comment]
You are welcome!
