### ISSUE TITLE
Extract wav audio

### ISSUE THREAD

**Issue by TayroneMatiello** [aliakseis/FFmpegPlayer#22]
Hello,
Your MFC code is very good. 

Could you inform us if there is a way to export a wav file from audio m_audioStream ?

Thank you in advance!

**Comment by aliakseis** [comment]
Hello,

Thank you very much for your interest!
If there aren't any specific requirements, I'd use the FFMpeg command line app to export a wav file though.

**Comment by TayroneMatiello** [comment]
Thank you!
I will try ffmpeg command line

**Comment by aliakseis** [comment]
Just in case: https://catswhocode.com/ffmpeg-commands/
