### ISSUE TITLE
Is the Direct2D rendering working ?

### ISSUE THREAD

**Issue by mediabuff** [aliakseis/FFmpegPlayer#3]
I get an exception on the following line, CPlayerView::updateFrame()

 HRESULT hr = yBitmap->CopyFromMemory(&destRect, data.image[0], data.pitch[0]);

**Comment by aliakseis** [comment]
Yes, the Direct2D rendering works. However, as for now, it is incompatible
with hardware acceleration. You need to hide #define USE_HWACCEL in the
ffmpegdecoder.cpp file.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by aliakseis** [comment]
Fixed in the latest revision

**Comment by mediabuff** [comment]
Thanks. Let me try it out later. Any plans for Directx 11 ?

**Comment by aliakseis** [comment]
Just added plain DirectX 9 support. It is controlled by #define USE_DXVA2 in PlayerView.h
