### ISSUE TITLE
Why you using boost?

### ISSUE THREAD

**Issue by topilski** [aliakseis/FFmpegPlayer#4]
Hi @aliakseis , i don't understand why you using boost, if the same functionality exists in std C++11 or higher.

**Comment by aliakseis** [comment]
Good question! Practically there is one reason: boost::thread::interrupt usage, but it came really handy.
And, there are other boost libraries used in the project as well.

**Comment by topilski** [comment]
Can you show in your code where you using boost::thread::interrupt mechanism?

**Comment by aliakseis** [comment]
Here it is:

inline void Shutdown(const std::unique_ptr<boost::thread>& th)
{
    if (th)
    {
        th->interrupt();
        th->join();
    }
}

Basically it is described here how it is helpful:
http://www.boost.org/doc/libs/1_66_0/doc/html/thread/thread_management.html#thread.thread_management.tutorial.interruption

In two words, it greatly simplifies thread termination. Due to this, it turned out to be easier just to restart threads during movie rewinding.

**Comment by aliakseis** [comment]
Sorry, there is another place where interrupt is used: in bool FFmpegDecoder::resetDecoding(...)

**Comment by topilski** [comment]
In any way if you call interrupt function you don't know how to stop your working thread from another thread? but it is wrong way, you should know lifetime of your thread and should know how to stop thread properly (may be stop flag, may be condition_variable notification or something else), or i something misunderstand?

**Comment by topilski** [comment]
In this line you have infinite loop, https://github.com/aliakseis/FFmpegPlayer/blob/6e6daeffb32b8d44dada4180505026e7e0752a0f/video/videoparserunnable.cpp#L65 but may be better have stop flag, than interrupt functionality?

**Comment by aliakseis** [comment]
boost::thread::interrupt gives more than a flag functionality
http://www.boost.org/doc/libs/1_66_0/doc/html/thread/thread_management.html#thread.thread_management.tutorial.interruption.predefined_interruption_points
If a thread stays waiting on one of these points, it will be terminated automatically right away.

**Comment by topilski** [comment]
cool, thank you for description!
