### ISSUE TITLE
[Bug] When I tried to use the mouse to change the time, the program crashed

### ISSUE THREAD

**Issue by tyrell-wallace** [aliakseis/FFmpegPlayer#40]
I'm using Windows 10 64-bit 22H2, and the latest FFmpegPlayer.

The file type in question was OPUS. The audio file had roughly 5 minutes.

As I tried to move the arrow with the mouse, it froze for a bit, then crashed with no error message.

Changing the time manually results in no issues.

When I tried doing it with a mkv file, it worked without issues. I assume it is a problem with OPUS files specifically

**Comment by aliakseis** [comment]
Seems to be fixed.

**Comment by tyrell-wallace** [comment]
I had no issues doing it this time. By the way, the audio sounds exceptionally crisp with this. Might also work as an audio player.

On another note, and I might put this into another issue if you want: Wouldn't it be nice if we could also set the time in 00:00 notation? It would make more sense since the time is displayed in 00:00 instead of just seconds. And as we're talking about time, is it doable to make it have the precision in the millisecond range? And/or a keyframe detection (and snapping) for better cuts in videos.

In any case, this is a great program. Its simplicity is beautiful
