### ISSUE TITLE
what is the purpose of allowDirect3dData in SetFrameFormat(FrameFormat format, bool allowDirect3dData)

### ISSUE THREAD

**Issue by mediabuff** [aliakseis/FFmpegPlayer#7]
SetFrameFormat(FrameFormat format, bool allowDirect3dData)

**Comment by aliakseis** [comment]
CPlayerView is able to use IDirect3DSurface9 objects provided by DXVA2 based accelerator directly, unlike CPlayerViewD2D. See FrameRenderingData struct usage.
