### ISSUE TITLE
今日头条互娱研发上海HR Sunny的问候

### ISSUE THREAD

**Issue by flysunnyDW** [aliakseis/FFmpegPlayer#9]
您好，我是今日头条互娱研发上海HR Sunny，有幸看到您的FFmpeg相关项目分享，希望有机会和您认识，不知道是否方便加个微信沟通，我的微信是fengzhigu-s，期待您的回复。

**Comment by aliakseis** [comment]
Thank you very much for your consideration!
I'd be glad to contact you. Unfortunately I am not in China now, and for some reason I can't install WeChat yet.
